name: myproject
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  file_picker: ^10.1.9
  intl: ^0.20.2
  video_player: ^2.7.0
  fl_chart: ^0.68.0 # IMPORTANT: Use a recent stable version
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.6.0
  firebase_core: ^3.13.0
  shared_preferences: ^2.5.3
  firebase_auth: ^5.5.3
  firebase_storage: ^12.4.6
  cloud_firestore: ^5.6.7  
  google_sign_in: ^6.3.0
  email_validator: ^3.0.0
  permission_handler: ^12.0.0+1
  phone_number_validator: ^0.0.1
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  http: ^1.4.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
   - assets/images/
  # If you want to use local fonts:
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: fonts/Inter-Regular.ttf
  #       - asset: fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: fonts/Inter-SemiBold.ttf
  #         weight: 600
  #       - asset: fonts/Inter-Bold.ttf
  #         weight: 700