// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE4vSj9VJv_CibA_Qd-NpYiugHI9YU0Sc',
    appId: '1:808014119846:web:da81b7cf85eb0a5d540567',
    messagingSenderId: '808014119846',
    projectId: 'speakora-48c46',
    authDomain: 'speakora-48c46.firebaseapp.com',
    storageBucket: 'speakora-48c46.firebasestorage.app',
    measurementId: 'G-39BC2BKZ6K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJm2YZIBFVl7XgkY7FspnZutQdTik6El4',
    appId: '1:808014119846:android:ba28a7b5c83bda55540567',
    messagingSenderId: '808014119846',
    projectId: 'speakora-48c46',
    storageBucket: 'speakora-48c46.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVC82wCK2teV7FSSwKCgzfHZhcp22V5Cs',
    appId: '1:808014119846:ios:bbf47114819a43a3540567',
    messagingSenderId: '808014119846',
    projectId: 'speakora-48c46',
    storageBucket: 'speakora-48c46.firebasestorage.app',
    iosBundleId: 'com.example.myproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVC82wCK2teV7FSSwKCgzfHZhcp22V5Cs',
    appId: '1:808014119846:ios:bbf47114819a43a3540567',
    messagingSenderId: '808014119846',
    projectId: 'speakora-48c46',
    storageBucket: 'speakora-48c46.firebasestorage.app',
    iosBundleId: 'com.example.myproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAE4vSj9VJv_CibA_Qd-NpYiugHI9YU0Sc',
    appId: '1:808014119846:web:55cbdfe9c1bf0515540567',
    messagingSenderId: '808014119846',
    projectId: 'speakora-48c46',
    authDomain: 'speakora-48c46.firebaseapp.com',
    storageBucket: 'speakora-48c46.firebasestorage.app',
    measurementId: 'G-8HF6W6JR47',
  );

}